# Generated by Django 4.2.7 on 2023-11-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("book_category", models.CharField(max_length=50)),
                ("book_description", models.TextField(max_length=10000)),
                ("book_rating", models.FloatField()),
                (
                    "book_image",
                    models.ImageField(
                        default="images/none/noimg.jpg", upload_to="images"
                    ),
                ),
            ],
        ),
    ]
